# Setup
title:               Rafael Pazini
tagline:             'rflpazini'
description:         'Personal site of Rafael'
url:                 https://rflpazini.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rafael Pazini 
  url:               https://twitter.com/rflpazini
  email:             rflpazini@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
