# Setup
title:               '@rflpazini'
tagline:             'Rafael Pazini'
description:         'Software engineer @MercadoLivre, caipira do interior paulista 🇧🇷, Open Source enthusiast and "I think I am an interesting person".'
url:                 https://rflpazini.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              '@rflpazini'
  url:               https://twitter.com/rflpazini
  email:             rflpazini@gmail.com

# Gems
plugins:
  - jekyll-paginate


# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

highlighter: rouge